from aibackends.llm.base import BaseProvider
from aibackends.tasks.llm.text_completion_task import TextCompletionTask
from unittest.mock import Mock, MagicMock

def test_task_id_generation():
    mock_provider = Mock(spec=BaseProvider)
    mock_provider.generate_text_completion = MagicMock(return_value="Mocked response")

    model = "test-model"

    """Test that task_id is autogenerated when not provided and uses provided value when set"""
    # Test 1: Task with provided task_id should use it
    task_with_id = TextCompletionTask(
        task_id="custom-task-123",
        name="Test Task With ID",
        provider=mock_provider,
        model=model,
        system_prompt="Test prompt",
        user_prompt="Test"
    )
    assert task_with_id.task_id == "custom-task-123", f"Expected task_id to be 'custom-task-123', got {task_with_id.task_id}"

    # Test 2: Task without task_id should have autogenerated UUID
    task_without_id = TextCompletionTask(
        name="Test Task Without ID",
        provider=mock_provider,
        model=model,
        system_prompt="Test prompt",
        user_prompt="Test"
    )

    assert task_without_id.task_id is not None, "task_id should not be None"
    assert len(task_without_id.task_id) > 0, "task_id should not be empty"
    assert task_without_id.task_id != "custom-task-123", "Autogenerated task_id should be different from custom task_id"

    # Test 3: Two tasks without task_id should have different autogenerated IDs
    task_without_id_2 = TextCompletionTask(
        name="Test Task Without ID 2",
        provider=mock_provider,
        model=model,
        system_prompt="Test prompt",
        user_prompt="Test"
    )
    assert task_without_id.task_id != task_without_id_2.task_id, "Two autogenerated task_ids should be different"

    # Verify that the provider was not called during initialization
    mock_provider.generate_text_completion.assert_not_called()

    print("✓ All task ID generation tests passed!")